key_regex = ''' \sa-zA-Z0-9!.\-='^#/!?>&'''

[[rules]]
    [rules.delimiter]
    open = "{{"
    close = "}}"

    [[rules.directives]]
    name = "Interpolation"
    command = ""
    iterator = "."

    [[rules.directives]]
    name = "EscapedInterpolation"
    command = "&"
    iterator = "."

    [[rules.directives]]
    name = "Section"
    command = "#"
    iterator = "."

    [[rules.directives]]
    name = "InvertedSection"
    command = "^"

    [[rules.directives]]
    name = "Close"
    command = "/"
    iterator = "."

    [[rules.directives]]
    name = "Partial"
    command = ">"

    [[rules.directives]]
    name = "Comment"
    command = "!"

[[rules]]
    [rules.delimiter]
    open = "{{{"
    close = "}}}"

    [[rules.directives]]
    name = "EscapedInterpolation"
    command = ""
    iterator = "."
